@extends('layouts.back')
@section('title', $incident->exists ? 'Modifier l’incident #'.$incident->id : 'Ajouter un incident')
@section('content')
<a href="{{ $incident->exists ? route('admin.incidents.show', $incident) : route('admin.incidents.index') }}" class="d-inline-block mb-4 text-primary">← Retour</a>
<div class="surface"><form method="POST" enctype="multipart/form-data" action="{{ $incident->exists ? route('admin.incidents.update', $incident) : route('admin.incidents.store') }}">@csrf @if($incident->exists) @method('PUT') @endif
<div class="row g-4">
<div class="col-md-6"><label class="form-label" for="equipment_id">Équipement</label><select class="form-select" id="equipment_id" name="equipment_id" required><option value="">Choisir un équipement</option>@foreach($equipments as $equipment)<option value="{{ $equipment->id }}" @selected((string) old('equipment_id', $incident->equipment_id) === (string) $equipment->id)>{{ $equipment->title }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label" for="user_id">Signalé par</label><select class="form-select" id="user_id" name="user_id" required><option value="">Choisir un utilisateur</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string) old('user_id', $incident->user_id) === (string) $user->id)>{{ $user->name }} ({{ $user->email }})</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label" for="severity">Gravité</label><select class="form-select" id="severity" name="severity" required>@foreach(\App\Models\Incident::SEVERITIES as $value => $label)<option value="{{ $value }}" @selected(old('severity', $incident->severity) === $value)>{{ $label }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label" for="status">Statut</label><select class="form-select" id="status" name="status" required>@foreach(\App\Models\Incident::STATUSES as $value => $label)<option value="{{ $value }}" @selected(old('status', $incident->status) === $value)>{{ $label }}</option>@endforeach</select></div>
<div class="col-12"><label class="form-label" for="description">Description</label><textarea class="form-control" id="description" name="description" rows="5" minlength="10" maxlength="2000" required>{{ old('description', $incident->description) }}</textarea></div>
<div class="col-12"><label class="form-label" for="photos">Ajouter des photos</label><input type="file" class="form-control" name="photos[]" id="photos" accept="image/jpeg,image/png,image/webp" multiple><small class="text-muted">JPG, PNG ou WebP · 5 Mo par image · 4 nouvelles photos maximum</small>
@if(!empty($incident->photos))<div class="gallery mt-3">@foreach($incident->photos as $photo)<label><img src="{{ asset($photo) }}" alt="Photo actuelle"><span class="d-block mt-2"><input type="checkbox" name="remove_photos[]" value="{{ $photo }}"> Retirer</span></label>@endforeach</div>@endif</div>
</div><div class="d-flex gap-3 mt-4"><button class="btn btn-primary px-4">{{ $incident->exists ? 'Enregistrer les modifications' : 'Créer' }}</button><a class="btn btn-outline-secondary" href="{{ route('admin.incidents.index') }}">Annuler</a></div></form></div>
@endsection
